name: dkakin
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # إدارة الحالة
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  equatable: ^2.0.5

  # قاعدة بيانات محلية
  sqflite: ^2.3.3+1
  # TODO-SQLCIPHER: استبدل sqflite بـ sqlcipher_flutter_libs للتشفير
  # sqlcipher_flutter_libs: ^0.6.0

  # حقن الاعتماديات
  get_it: ^7.7.0

  # رسوم بيانية
  fl_chart: ^0.68.0

  # فتح روابط خارجية (واتساب/SMS)
  url_launcher: ^6.3.0

  # تخزين محلي بسيط
  shared_preferences: ^2.2.3

  # مسارات الملفات
  path_provider: ^2.1.4

  # تشفير
  crypto: ^3.0.5

  # معرّفات UUID
  uuid: ^4.4.2

  # ماسح الباركود
  # TODO: أضف صلاحية الكاميرا في AndroidManifest.xml
  mobile_scanner: ^5.1.1

  # طابعة بلوتوث
  # TODO: أضف صلاحيات BLUETOOTH في AndroidManifest.xml
  # esc_pos_bluetooth: ^0.4.0

  # توطين وتنسيق
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # TODO: أضف خط Cairo للعربية
  # fonts:
  #   - family: Cairo
  #     fonts:
  #       - asset: assets/fonts/Cairo-Regular.ttf
  #       - asset: assets/fonts/Cairo-Bold.ttf
  #         weight: 700

  # TODO: أضف أيقونة التطبيق
  # flutter_launcher_icons:
  #   android: "launcher_icon"
  #   ios: true
  #   image_path: "assets/icon/dkakin_icon.png"
  #   adaptive_icon_background: "#2E7D32"
