name: Build Dkakin APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Flutter 3.27.2
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.2'
          channel: 'stable'

      # تنظيف عميق لكل ما يخص Gradle (حتى العام)
      - name: Deep clean everything
        run: |
          flutter clean
          rm -rf android/.gradle android/app/build
          rm -rf ~/.gradle
          rm -rf ~/.m2/repository
          rm -rf $PUB_CACHE

      - name: Get packages
        run: flutter pub get

      - name: Build APK release
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
